config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'thanks' => 'home#thanks', as: :home_thanks
  get 'register_fin' => 'home#register_fin', as: :home_register_fin
  get 'test' => 'home#test', as: :home_test
  get 'dbindex' => 'home#dbindex', as: :home_dbindex
  get 'detailscout' => 'home#detailscout', as: :home_detailscout
  get 'firstscout' => 'home#firstscout', as: :home_firstscout

  #ユーザーログイン後のユーザメニューへのルーティング
  #求職者(=ユーザー)のメニュー画面
  scope :user_menu do
      get '' => 'user_menu#index', as: :user_menu

      #履歴書のルーティング
      scope :resume do
          get '' => 'users#index', as: :resume
          get 'show' => 'users#show', as: :show_resume
          get 'edit' => 'users#edit', as: :edit_resume
          post 'edit' => 'users#update', as: ''
          patch 'edit' => 'users#update', as: ''
      end

      #職歴のルーティング
      resources :careers
    #  scope :careers do
    #      get '' => 'careers#index', as: :careers
    #      get 'new' => 'careers#new', as: :new_careers
    #      post 'create' => 'careers#create', as: ''
    #      get 'show' => 'careers#show', as: :show_careers
    #      get 'edit' => 'careers#edit', as: :edit_careers
    #      post 'edit' => 'careers#update', as: ''
    #      patch 'edit' => 'careers#update', as: ''
    #  end

      #設定ページのルーティング
      scope :user_setting do
          get ''   => 'user_setting#index', as: :user_setting
          get 'viewconfig'   => 'user_setting#viewconfig', as: :user_setting_viewconfig
          get 'byebye'       => 'user_setting#byebye', as: :user_setting_byebye
          get 'logininfo'    => 'user_setting#logininfo', as: :user_setting_logininfo
          get 'popupconfig'  => 'user_setting#popupconfig', as: :user_setting_popupconfig
          get 'byebyeresult' => 'user_setting#byebyeresult', as: :user_setting_byebyeresult
          post 'byebyeaccept' => 'user_setting#byebyeaccept', as: :user_setting_byebyeaccept
      end

      #スカウトページのルーティング
      scope :scout_views do
          get '' => 'scout_views#index', as: :scout_views
          get 'detail' => 'scout_views#detail', as: :scout_view_detail
          get 'agree_window' => 'scout_views#agree_window' , as: :scout_view_agree_window
          get 'agree' => 'scout_views#agree' , as: :scout_view_agree
      end

      #スカウトメッセージのメニュー画面
      scope :scout_messages do
          get '' => 'scout_messages#index', as: :scout_messages
      end
  end


  #求人会社(=client)のメニュー画面
  scope :client_menu do
      get '' => 'client_menu#index' ,as: :client_menu

          #企業情報編集ページのルーティング
          scope :coinfo do
              get '' => 'clients#index', as: :coinfo
              get 'show' => 'clients#show', as: :show_coinfo
              get 'edit' => 'clients#edit', as: :edit_coinfo
              post 'edit' => 'clients#update', as: ''
              patch 'edit' => 'clients#update', as: ''
          end

          scope :client_setting do

              get '' => 'client_setting#index'  ,as: :client_setting
                  get 'accountsetting' => 'client_setting#accountsetting' ,as: :client_setting_accountsetting
                  get 'template'       => 'client_setting#template'       ,as: :client_setting_template
                  get 'logininfo'      => 'client_setting#logininfo'      ,as: :client_setting_logininfo
                  get 'popupconfig'    => 'client_setting#popupconfig'    ,as: :client_setting_popupconfig
                  get 'accountdelete'  => 'client_setting#accountdelete'  ,as: :client_setting_accountdelete
          end

          scope :scout_checks do
            get '' => 'scout_checks#index' , as: :scout_checks
          end

          scope :scout_manage do
            get '' => 'scout_manage#index' , as: :scout_manage
          end

  end

 # スカウトページへのルーティング
 resources :scouts

 scope :scouts do

   #スカウトページでユーザー情報閲覧ルーティング
   scope :user_views do
     get 'show' => 'user_views#show' ,as: :user_views_show
   end

 end
   #職歴のルーティング
   #resources :careers

  #static_pagesへのルーティング
  get '/companysummary' => 'static_pages#companysummary'
  get '/contactus'      => 'static_pages#contactus'
  get '/convention'     => 'static_pages#convention'
  get '/faq'            => 'static_pages#faq'
  get '/privacypolicy'  => 'static_pages#privacypolicy'

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmation: 'users/confirmations',
      unlooks: 'users/unlooks',
      passwords: 'users/passwords'
    }

  devise_for :clients, controllers: {
      registrations: 'clients/registrations',
      sessions: 'clients/sessions',
      confirmations: 'clients/confirmations',
      unlooks: 'clients/unlooks',
      passwords: 'clients/passwords'
    }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # layout "clienttest"
  def index
    render :layout => 'application'
  end

  # 仮登録thanks
  def thanks
    render :layout => 'static_application'
  end

  # 本登録thanks
  def register_fin
    render :layout => 'static_application'
    now = Time.now
    @user = User.find_by(email: params[:email])
    @user.update(:confirmed_at => now)
  end

  def test
    render :layout => 'client_application'
  end

  def dbindex
    render :layout => 'client_application'
  end

  def detailscout
    render :layout => 'client_application'
  end

  def firstscout
    render :layout => 'client_application'
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dbindex.html.erb
<div class="content_upper">
  <h2>求職者を探す</h2>
</div> <!--content_upper -->
<div class="content_container">
  <div class="search-box">
    <table class="table_1">
      <tr>
      <th>年齢</th>
      <td>
        <div class="over_text_col">
          <select>
            <option value="test1"></option>
            <option value="test1">test1</option>
            <option value="test2">test2</option>
            <option value="test3">test3</option>
            <option value="test4">test4</option>
            <option value="test5">test5</option>
          </select>
        </div>
      <p class="ndash">〜</p>
      <div class="over_text_col">
          <select>
            <option value="test1"></option>
            <option value="test1">test1</option>
            <option value="test2">test2</option>
            <option value="test3">test3</option>
            <option value="test4">test4</option>
            <option value="test5">test5</option>
          </select>
      </div>
    </td>
      </tr>
      <tr>
      <th>希望年収</th>
      <td>
        <div class="over_text_col">
            <select>
              <option value="test1"></option>
              <option value="test1">test1</option>
              <option value="test2">test2</option>
              <option value="test3">test3</option>
              <option value="test4">test4</option>
              <option value="test5">test5</option>
            </select>
        </div>
        <p class="ndash">〜</p>
        <div class="over_text_col">
            <select>
              <option value="test1"></option>
              <option value="test1">test1</option>
              <option value="test2">test2</option>
              <option value="test3">test3</option>
              <option value="test4">test4</option>
              <option value="test5">test5</option>
            </select>
        </div>
      </td>
      </tr>
      <tr>
        <th>希望職種</th>
        <td>
          <div class="checkbox_col">
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">測量士</span>
            </label>
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">測量士補</span>
            </label>
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">設計士</span>
            </label>
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">CAP<br>オペレーター</span>
            </label>
          </div> <!--checkbox_col -->
          <div class="checkbox_col">
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">施工管理</span>
            </label>
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">積算</span>
            </label>
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">営業</span>
            </label>
          </div> <!--checkbox_col -->
        </td>
      </tr>
      <tr>
        <th>希望雇用形態</th>
        <td>
          <div class="checkbox_col">
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">正社員</span>
            </label>
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">契約社員</span>
            </label>
            <label class="labeltag">
              <input type="checkbox" name="checkbox01[]" class="checkbox01-input">
              <span class="checkbox01-parts">アルバイト・パート</span>
            </label>
          </div> <!--checkbox_col -->
        </td>
      </tr>
      <tr>
        <th>資格有無</th>
        <td>
          <div class="radio02">
          <input type="radio" name="radio02" class="radio02-input" id="radio02-01">
          <label for="radio02-01">ラジオ01</label>
          <input type="radio" name="radio02" class="radio02-input" id="radio02-02">
          <label for="radio02-02">ラジオ02</label>
        </div>
        </td>
      </tr>
    </table>
  </div> <!--search-box -->
  <div class="button_group">
    <a href="#" class="search_btn">検索</a>
  </div> <!--button_group -->
  <div class="search-result">
    <h2>113件</h2>
  </div><!--search-result -->
  <div class="search-index-box">
      <div class="frame_index">
        <div class="content">
          <div class="frame-head">
            <p>ID:９９３さん</p>
          </div><!--frame-head -->
          <div class="frame-middle1">
            <div class="left-character">
              <ul>
                <li>男性</li>
                <li>35才</li>
                <li>希望年収500万円以上</li>
              </ul>
            </div>
            <div class="right-character">
              <div class="tag-3">
                <p>資格あり</p>
              </div>
            </div>
          </div><!--frame-middle1 -->
          <div class="frame-middle2">
            <div class="tag">
              <span class="tag-4">正社員</span>
              <span class="tag-4">契約社員</span>
            </div>
          </div><!--frame-middle2 -->
          <div class="frame-bottom">
            <div class="tag">
              <span class="tag_2">測量士</span>
              <span class="tag_2">測量士補</span>
            </div>
          </div><!--frame-bottom -->
        </div><!--content -->
      </div><!--frame_index -->
      <div class="frame_index">
        <div class="content">
          <div class="frame-head">
            <p>ID:９９３さん</p>
          </div><!--frame-head -->
          <div class="frame-middle1">
            <div class="left-character">
              <ul>
                <li>男性</li>
                <li>35才</li>
                <li>希望年収500万円以上</li>
              </ul>
            </div>
            <div class="right-character">
              <div class="tag-3">
                <p>資格あり</p>
              </div>
            </div>
          </div><!--frame-middle1 -->
          <div class="frame-middle2">
            <div class="tag">
              <span class="tag-4">正社員</span>
              <span class="tag-4">アルバイト・パート</span>
            </div>
          </div><!--frame-middle2 -->
          <div class="frame-bottom">
            <div class="tag">
              <span class="tag_2">CAD・オペレーター</span>
              <span class="tag_2">設計士</span>
            </div>
          </div><!--frame-bottom -->
        </div><!--content -->
      </div><!--frame_index -->
      <div class="frame_index">
        <div class="content">
          <div class="frame-head">
            <p>ID:９９３さん</p>
          </div><!--frame-head -->
          <div class="frame-middle1">
            <div class="left-character">
              <ul>
                <li>男性</li>
                <li>35才</li>
                <li>希望年収500万円以上</li>
              </ul>
            </div>
            <div class="right-character">
              <div class="tag-3">
                <p>資格あり</p>
              </div>
            </div>
          </div><!--frame-middle1 -->
          <div class="frame-middle2">
            <div class="tag">
              <span class="tag-4">正社員</span>
              <span class="tag-4">アルバイト・パート</span>
            </div>
          </div><!--frame-middle2 -->
          <div class="frame-bottom">
            <div class="tag">
              <span class="tag_2">測量士</span>
              <span class="tag_2">測量士補</span>
              <span class="tag_2">施工管理</span>
            </div>
          </div><!--frame-bottom -->
        </div><!--content -->
      </div><!--frame_index -->
      <div class="pagination-wrapper">
        <div class="pagination-orgin">
          <a class="prev page-numbers" href="javascript:;">prev</a>
          <span aria-current="page" class="page-numbers current">1</span>
          <a class="page-numbers" href="javascript:;">2</a>
          <a class="page-numbers" href="javascript:;">3</a>
          <a class="page-numbers" href="javascript:;">4</a>
          <a class="page-numbers" href="javascript:;">5</a>
          <a class="page-numbers" href="javascript:;">6</a>
          <a class="page-numbers" href="javascript:;">7</a>
          <a class="page-numbers" href="javascript:;">8</a>
          <a class="page-numbers" href="javascript:;">9</a>
          <a class="page-numbers" href="javascript:;">10</a>
          <a class="next page-numbers" href="javascript:;">next</a>
        </div>
      </div>
  </div><!--search-index-box -->
</div> <!--content_container -->

app/views/home/detailscout.html.erb
<div class="content_container">
  <div class="user-detail">
    <div class="detail-head">
      <div class="user-name">
        <h3>ID933さん</h3>
      </div><!--user-name -->
      <div class="left-character">
        <ul>
          <li>男性</li>
          <li>35才</li>
          <li>希望年収500万円以上</li>
        </ul>
      </div><!--left-character -->

      <div class="btns-scout-clip">
        <a href="#" class="scout-btn">スカウトを送る</a>
        <a href="#" class="clip-btn">クリップ</a>
      </div><!--btn-scout-clip -->
    </div><!--detail-head -->

    <div class="detail-middle">
      <div class="display-conditions">
        <div class="display-title">
          <h3>希望条件</h3>
        </div><!--display-title -->
        <div class="display-detail">
          <div class="dis-condisons-detail">
            <table class="table_1">
              <tr>
              <th>希望年収</th>
              <td><p>500万円〜700万円</p></td>
              </tr>
              <tr>
              <th>希望雇用形態</th>
              <td>
                <ul>
                  <li>正社員</li>
                  <li>アルバイト・パート</li>
                  <li>契約社員</li>
                </ul>
              </td>
              </tr>
              <tr>
              <th>希望職種</th>
              <td>
                <ul>
                  <li>測量士</li>
                  <li>測量士補</li>
                  <li>設計士</li>
                  <li>CADオペレーター</li>
                </ul>
              </td>
              </tr>
            </table><!--table -->
          </div><!--dis-condisons-detail -->
        </div><!--display-detail -->
      </div><!--display-conditions -->

      <div class="display-certifications">
        <div class="display-title">
          <h3>保有資格</h3>
        </div><!--display-title -->
        <div class="display-detail">
          <div class="dis-certifications-detail">
            <table class="table_1">
              <tr>
              <th>保有資格</th>
              <td>
                <ul>
                  <li>施工管理技師</li>
                  <li>国家資格測量士資格</li>
                  <li>CADオペレーター2級</li>
                  <li>1級建築士</li>
                  <li>ドローン操作取り扱い</li>
                </ul>
              </td>
              </tr>
            </table><!--table -->
          </div><!--dis-certifications-detail -->
        </div><!--display-detail -->
      </div><!--display-certifications -->

      <div class="display-careers">
        <div class="display-title">
          <h3>経歴</h3>
        </div><!--display-title -->
        <div class="display-detail">
          <div class="dis-careers-detail">
            <div class="career-containers">
              <div class="career-title">
                <p>経歴1</p>
              </div><!--career-title -->
              <div class="career-table">
                <table class="table_1">
                  <tr>
                  <th>会社名</th>
                  <td>
                    <ul>
                      <li>安達測量株式会社</li>
                    </ul>
                  </td>
                  </tr>
                  <tr>
                  <th>就労期間</th>
                  <td>
                    <ul>
                      <li>2018年1月〜2018年6月</li>
                    </ul>
                  </td>
                  </tr>
                  <tr>
                  <th>雇用形態</th>
                  <td>
                    <ul>
                      <li>正社員</li>
                    </ul>
                  </td>
                  </tr>
                  <tr>
                  <th>業務内容</th>
                  <td>
                    <ul>
                      <li>プレイングマネージャーとして10人のマネジメントと共に測量現場管理も行なっておりました。</li>
                    </ul>
                  </td>
                  </tr>
                </table><!--table_1 -->
              </div><!--career table -->
            </div><!--career-countainers -->
            <div class="career-containers">
              <div class="career-title">
                <p>経歴2</p>
              </div><!--career-title -->
              <div class="career-table">
                <table class="table_1">
                  <tr>
                  <th>会社名</th>
                  <td>
                    <ul>
                      <li>添田株式会社</li>
                    </ul>
                  </td>
                  </tr>
                  <tr>
                  <th>就労期間</th>
                  <td>
                    <ul>
                      <li>2017年1月〜2017年12月</li>
                    </ul>
                  </td>
                  </tr>
                  <tr>
                  <th>雇用形態</th>
                  <td>
                    <ul>
                      <li>アルバイト・パート</li>
                    </ul>
                  </td>
                  </tr>
                  <tr>
                  <th>業務内容</th>
                  <td>
                    <ul>
                      <li>測量士補として現場労働を行なっておりました。</li>
                    </ul>
                  </td>
                  </tr>
                </table><!--table_1 -->
              </div><!--career table -->
            </div><!--career-countainers -->
          </div><!--dis-careers-detail -->
        </div><!--display-detail -->
      </div><!--display-careers -->

      <div class="display-educations">
        <div class="display-title">
          <h3>最終学歴</h3>
        </div><!--display-title -->
        <div class="display-detail">
          <div class="dis-educations-detail">
            <table class="table_1">
              <tr>
              <th>学校名</th>
              <td>
                <ul>
                  <li>千葉大学</li>
                </ul>
              </td>
              </tr>
              <tr>
              <th>卒業学部・学科</th>
              <td>
                <ul>
                  <li>理工学部建築学科</li>
                </ul>
              </td>
              </tr>
              <tr>
              <th>卒業年</th>
              <td>
                <ul>
                  <li>2008年3月</li>
                </ul>
              </td>
              </tr>
            </table><!--table_1 -->
          </div><!--dis-educations-detail -->
        </div><!--display-detail -->
      </div><!--display-educations -->

    </div><!--detail-middle -->

    <div class="detail-bottom-btn">
      <div class="btns-scout-clip">
        <a href="#" class="scout-btn">スカウトを送る</a>
        <a href="#" class="clip-btn">クリップ</a>
      </div><!--btn-scout-clip -->
    </div><!--detail-bottom-btn -->

  </div><!--user-detail -->
</div><!--content_container -->

app/views/home/index.html.erb
<!-- FIXED:トップ画像はguideボタン以外は貼り付け　後日リファクタリング

-->
<!-- FIXED:特徴とSTEPのパネル高さがグリッドで揃わない

-->

<!-- Must FIXED:スマホ用レイアウト整える

-->


<div class="top-full-container">
  <div class="pc-main-visual" style= "background-image:url(<%= asset_path "bg-main-visual-pc03.jpg"%>)">
    <%= link_to "まずは無料登録！", new_user_registration_path, onclick: "ga('send', 'event', 'click', 'form_tap', {'nonInteraction': 1});", class: "top-guide-message-btn" %>
    <a href="/users/sign_in" class="top-guide-login-btn">登録済みの</br>方はこちら</a>
  </div>
  <div class="sp-main-visual" style= "background-image:url(<%= asset_path "bg-main-visual-sp03.jpg"%>)">
    <a href="/users/sign_up" class="top-guide-message-btn">まずはカンタン無料登録！</a>
    <a href="/users/sign_in" class="top-guide-login-btn">登録済みの</br>方はこちら</a>
  </div>

  <div class="top-point-container">
    <div class="top-point-title">
      <div class="top-point-title-en">
        <h2>POINT</h2>
      </div><!--top-point-title -->
      <div class="top-point-title-ja">
        <h3>【ジョブ建設 測量・設計】<br class="br-sp" />３つの特徴</h3>
      </div><!--top-point-title -->
    </div><!--top-point-title -->
    <div class="three-boxes-container">
      <div class="row">
        <div class="row-eq-height">
          <div class="col-md-4">
            <div class="inner-box">
                <%= image_tag("point/point01-specialized.gif", :alt => "特徴01測量・設計に特化アイコン") %>
                <h3>測量・設計に特化</h3>
                <p>ジョブ建設は測量、設計に特化した転職スカウトサービスです。あなたの技術や経験を生かす事のできる転職を支援いたします。</p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="inner-box">
                <%= image_tag("point/point02-scout.gif", :alt => "特徴02スカウト受取りアイコン") %>
                <h3>スカウトを受け取る</h3>
                <p>プロフィール登録(無料)をしていただければ、あなたをスカウトしたい企業からのスカウトメールを待つだけです。</p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="inner-box">
                <%= image_tag("point/point03-anonymous.gif", :alt => "特徴03完全匿名性アイコン") %>
                <h3>完全匿名制</h3>
                <p>企業からのスカウトメールに返信や受諾をするまでは、氏名、生年月日、メールアドレス等の個人情報は完全に非公開です。在職中の方でも安心してご利用いただけます。</p>
              </div>
            </div>
        </div><!--row-eq-height -->
      </div><!--row -->
     </div><!--three-boxes-container -->
    </div><!--top-point-container -->

    <div class="section-flow">
      <h2>登録無料！簡単！<br class="br-sp" />３STEP！</h2>
      <div class="step-visual" style= "background-image:url(<%= asset_path "bg-step-img-pc.jpg"%>)">

        <div class="top-step-title">
          <div class="top-step-title-en">
            <h3>STEP</h3>
          </div><!--top-point-title -->
          <div class="top-step-title-ja">
            <p>【ジョブ建設 測量・設計】<br class="br-sp" />３つのステップ</p>
          </div><!--top-point-title -->
        </div><!--top-point-title -->

        <div class="three-boxes-container">
        <div class="row">
          <div class="row-eq-height">
            <div class="col-md-4">
              <div class="inner-box">
              <%= image_tag("step/step01-register.gif", :alt => "ステップ01プロフィール登録アイコン") %>
              <h3>プロフィールを登録</h3>
              <p>基本情報、希望条件、保有資格などを登録します。</p>
            </div>
            </div>
            <div class="step-arrow01">
              <%= image_tag("img-right-arrow.svg", :alt => "右矢印") %>
            </div>
            <div class="col-md-4">
              <div class="inner-box">
              <%= image_tag("step/step02-wait.gif", :alt => "ステップ02スカウト待ちアイコン") %>
              <h3>スカウトメールを待つ</h3>
              <p>登録した後はあなたをスカウトしたい企業からのスカウトを待ちます。</p>
              </div>
            </div>
            <div class="step-arrow02">
              <%= image_tag("img-right-arrow.svg", :alt => "右矢印") %>
            </div>
            <div class="col-md-4">
              <div class="inner-box">
              <%= image_tag("step/step03-contact.gif", :alt => "ステップ03企業とコンタクトアイコン") %>
              <h3>企業とコンタクト</h3>
              <p>スカウトメールの条件や求人内容を確認し、気になった企業に返信しコンタクトをとりましょう。</p>
            </div>
          </div>
          </div>
        </div>
      </div>
      <div class="guide-btn-container">
        <div class="balloon1">
          <p>簡単１０秒！<br class="br-sp" />まずはメールアドレスを登録！</p>
        </div>
        <%= link_to "まずは無料登録！", new_user_registration_path, class: "top-guide-message-btn", :onclick => "ga('send', 'event', 'click', 'form_tap', {'nonInteraction': 1});" %>
      </div>
      </div>
    </div><!--section-flow-->

  <div class="top-section-faq">
      <div class="top-point-title">
        <div class="top-point-title-en">
          <h2>FAQ</h2>
        </div><!--top-point-title -->
        <div class="top-point-title-ja">
          <h3>よくあるご質問</h3>
        </div><!--top-point-title -->
      </div><!--top-point-title -->
    <div class="display-faq">
      <div class="faq">
        <div class="display-detail">
          <dl>
            <dt><span>Q.</span>利用するには費用がかかりますか？</dt>
            <dd><span>A.</span>企業様からいただいており、みなさまは全て無料でご利用できます。</dd>

            <dt><span>Q.</span>プロフィールとして登録した情報のうち、企業に公開される項目は？</dt>
            <dd><span>A.</span>お名前、電話番号、メールアドレス、誕生日の個人情報項目は、企業からのスカウトメールに承諾返信した場合のみ該当企業に公開されます。</dd>

            <dt><span>Q.</span>業務委託、契約社員、アルバイト、学生でも登録可能でしょうか？</dt>
            <dd><span>A.</span>はい、可能です。正社員に限らずスカウトが届きます。</dd>

            <dt><span>Q.</span>測量や設計の経験がなくても登録可能でしょうか？</dt>
            <dd><span>A.</span>はい、可能です。未経験者の方もスカウトが届きます。</dd>

            <dt><span>Q.</span>スカウトメールが届いた後の流れは？</dt>
            <dd><span>A.</span>スカウト企業様の情報をみて、選考へ進みたい場合のみ、承諾ボタンを押していただきます。承諾しますとお名前、メールアドレスなどの個人情報が開示されますので、企業様と直接やりとりをおこない、選考へ進んでいただきます。</dd>
          </dl>
        </div><!--display-detail -->
      </div><!--user-faq -->
    </div><!--display-faq -->
  </div><!--top-section-faq -->

<!-- ここから下は、デプロイ時点では無効化しておく  2018.7.31 by takuya-->


  <div class="top-section-contact" id="contact">
    <div class="top-contact-title">
      <h2>ご利用は無料です！</h2>
    </div><!--top-contact-title -->
    <div class="top-contact-container">
      <div class="top-contact-flow">
        <ul class="flow_contact">
          <li class="active">メールアドレス入力</li>
          <li>仮登録メール確認</li>
          <li >会員情報入力</li>
        </ul>
      </div><!--top-contact-flow -->
      <div class="top-contact-mail-term-link">
        <!-- <ul>
          <li><%= link_to "『利用規約』" , convention_path %></li>
          <li><%= link_to "『プライバシーポリシー』" , privacypolicy_path %></li>
        </ul> -->
      </div><!--top-contact-mail-term-link -->
      <div class="top-contact-btn">
        <%= link_to "まずは無料登録！", new_user_registration_path, class: "top-guide-message-btn", :onclick => "ga('send', 'event', 'click', 'form_tap', {'nonInteraction': 1});" %>
      </div><!--top-contact-btn -->
      <div class="top-contact-caution">
        <ul>
          <li>※メールによる認証が必要となります。すぐに受け取れるメールアドレスをご入力ください。</li>
          <li>※メール受信制限をされている方は ジョブ建設運営部からの</br>メール受信を許可してください。</li>
        </ul>
      </div><!--top-contact-caution -->
    </div><!--top-contact-container -->
  </div><!--top-section-contact -->
</div><!--full-container -->
<%= render 'layouts/footer' %>

app/views/home/register_fin.html.erb
<div class="setting-container-detail">
  <h2>本登録が終了しました。</h2>
  <div class="registration-container">
  <div class="mail_text">
    <h3>今後の流れ</h3>
    <p>ご登録ありがとうございます。入力していただきましたメールアドレスとパスワードにて以下リンクにてログイン可能となっております。</p>
    <div class="guide-login">
      <%= link_to "ログイン画面", new_user_session_path %>
    </div>
    <p>また、履歴書にある電話番号を入力いただけましたらサービスや入力情報について運営スタッフより電話(050-3187-4372)にてご連絡いたします。何卒よろしくお願いいたします。</p>
  </div>
</div>
</div>

app/views/home/thanks.html.erb
<div class="setting-container-detail">
  <h2>仮登録ありがとうございます。</h2>
  <div class="registration-container">
  <div class="mail_text">
    <p>いただきましたメールアドレスへ認証メールを送付しております。</br>
      リンクをクリックしていただくと登録完了となります。
    </p>
  </div>
</div>
</div>