config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'thanks' => 'home#thanks', as: :home_thanks
  get 'register_fin' => 'home#register_fin', as: :home_register_fin
  get 'test' => 'home#test', as: :home_test
  get 'dbindex' => 'home#dbindex', as: :home_dbindex
  get 'detailscout' => 'home#detailscout', as: :home_detailscout
  get 'firstscout' => 'home#firstscout', as: :home_firstscout

  #ユーザーログイン後のユーザメニューへのルーティング
  #求職者(=ユーザー)のメニュー画面
  scope :user_menu do
      get '' => 'user_menu#index', as: :user_menu

      #履歴書のルーティング
      scope :resume do
          get '' => 'users#index', as: :resume
          get 'show' => 'users#show', as: :show_resume
          get 'edit' => 'users#edit', as: :edit_resume
          post 'edit' => 'users#update', as: ''
          patch 'edit' => 'users#update', as: ''
      end

      #職歴のルーティング
      resources :careers
    #  scope :careers do
    #      get '' => 'careers#index', as: :careers
    #      get 'new' => 'careers#new', as: :new_careers
    #      post 'create' => 'careers#create', as: ''
    #      get 'show' => 'careers#show', as: :show_careers
    #      get 'edit' => 'careers#edit', as: :edit_careers
    #      post 'edit' => 'careers#update', as: ''
    #      patch 'edit' => 'careers#update', as: ''
    #  end

      #設定ページのルーティング
      scope :user_setting do
          get ''   => 'user_setting#index', as: :user_setting
          get 'viewconfig'   => 'user_setting#viewconfig', as: :user_setting_viewconfig
          get 'byebye'       => 'user_setting#byebye', as: :user_setting_byebye
          get 'logininfo'    => 'user_setting#logininfo', as: :user_setting_logininfo
          get 'popupconfig'  => 'user_setting#popupconfig', as: :user_setting_popupconfig
          get 'byebyeresult' => 'user_setting#byebyeresult', as: :user_setting_byebyeresult
          post 'byebyeaccept' => 'user_setting#byebyeaccept', as: :user_setting_byebyeaccept
      end

      #スカウトページのルーティング
      scope :scout_views do
          get '' => 'scout_views#index', as: :scout_views
          get 'detail' => 'scout_views#detail', as: :scout_view_detail
          get 'agree_window' => 'scout_views#agree_window' , as: :scout_view_agree_window
          get 'agree' => 'scout_views#agree' , as: :scout_view_agree
      end

      #スカウトメッセージのメニュー画面
      scope :scout_messages do
          get '' => 'scout_messages#index', as: :scout_messages
      end
  end


  #求人会社(=client)のメニュー画面
  scope :client_menu do
      get '' => 'client_menu#index' ,as: :client_menu

          #企業情報編集ページのルーティング
          scope :coinfo do
              get '' => 'clients#index', as: :coinfo
              get 'show' => 'clients#show', as: :show_coinfo
              get 'edit' => 'clients#edit', as: :edit_coinfo
              post 'edit' => 'clients#update', as: ''
              patch 'edit' => 'clients#update', as: ''
          end

          scope :client_setting do

              get '' => 'client_setting#index'  ,as: :client_setting
                  get 'accountsetting' => 'client_setting#accountsetting' ,as: :client_setting_accountsetting
                  get 'template'       => 'client_setting#template'       ,as: :client_setting_template
                  get 'logininfo'      => 'client_setting#logininfo'      ,as: :client_setting_logininfo
                  get 'popupconfig'    => 'client_setting#popupconfig'    ,as: :client_setting_popupconfig
                  get 'accountdelete'  => 'client_setting#accountdelete'  ,as: :client_setting_accountdelete
          end

          scope :scout_checks do
            get '' => 'scout_checks#index' , as: :scout_checks
          end

          scope :scout_manage do
            get '' => 'scout_manage#index' , as: :scout_manage
          end

  end

 # スカウトページへのルーティング
 resources :scouts

 scope :scouts do

   #スカウトページでユーザー情報閲覧ルーティング
   scope :user_views do
     get 'show' => 'user_views#show' ,as: :user_views_show
   end

 end
   #職歴のルーティング
   #resources :careers

  #static_pagesへのルーティング
  get '/companysummary' => 'static_pages#companysummary'
  get '/contactus'      => 'static_pages#contactus'
  get '/convention'     => 'static_pages#convention'
  get '/faq'            => 'static_pages#faq'
  get '/privacypolicy'  => 'static_pages#privacypolicy'

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmation: 'users/confirmations',
      unlooks: 'users/unlooks',
      passwords: 'users/passwords'
    }

  devise_for :clients, controllers: {
      registrations: 'clients/registrations',
      sessions: 'clients/sessions',
      confirmations: 'clients/confirmations',
      unlooks: 'clients/unlooks',
      passwords: 'clients/passwords'
    }

end

app/models/scout.rb
class Scout < ApplicationRecord
    belongs_to :user
    belongs_to :client
    has_many :scouts_message
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationClientController
  layout "client_application"
  def index
    @client = Client.find_by(id: current_client.id)
    if @client.name == nil then
      redirect_to coinfo_path #Ajaxなどでメッセージボックスで履歴書登録が必要であるというメッセージをクライアントへ伝える。
    end
    @scout = Scout.where(client_id: @client.id)
    @user = User.all.order(created_at: "DESC")
  end

  def new
    @scout = Scout.new
    @user = User.find(params[:user_id])
    @client = Client.find_by(id: current_client.id)
    @scout.user_id = @user.id
    @scout.client_id = current_client.id

  end

  def show
    @scout = Scout.find(params[:id])
    @user = User.find_by(id: @scout.user_id)
    @scout.client_id = current_client.id
  end

  def create
    @scout = Scout.new(scout_params)
    @user = User.find_by(id: @scout.user_id)
    @scout.client_id = current_client.id
    @scout.update(agreement_count: 0)

    if @scout.save
      redirect_to scout_path(@scout)
    else
      render action: :new
    end
  end

  def edit
    @scout = Scout.find(params[:id])
  end

  def update
    @scout = Scout.find(params[:id])
    @scout.update(scout_params)
    redirect_to scouts_path(@scout)
  end


  private
    def scout_params
      params.require(:scout).permit(
        :agreement_count,
        :summary,
        :content,
        :client_id,
        :user_id
        )
    end

end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/views/scouts/_form.html.erb
<h2> ID:<%= @user.number_id %>さん </h2>

<%= form_with model: @scout, local: true do |form| %>

  <div class="has-float-label_full_lg">
    <p class="must_btton_text">必須</p>
    <%= form.label :summary, 'サマリ' %>
    <%= form.text_field :summary, id: 'scout_summary', placeholder: "お願いします" %>
  </div>

  <div class="has-float-label_full_lg">
    <p class="must_btton_text">必須</p>
    <%= form.label :content, '詳細' %>
    <%= form.text_area :content, id: 'scout_content', placeholder: "弊社でぜひ、あなたの力を生かしてみませんか？" %>
  </div>

  <%= form.hidden_field :user_id ,:value => @user.id %>


  <%= form.submit :送信, class: 'basic-btn' %>
<% end %>

app/views/scouts/index.html.erb
<div class="content_upper">
  <h3>求職者一覧ページ</h3>
</div>

<div class="setting-container-detail">
    <div class="scout-job-content-index">
      <% @user.each do |u| %>
          <% if u.last_name_kana? then %>
            <div class="frame_index">
                <div class="text">
                  <p>ID <%= u.number_id %> さん</p>
                  <p>希望年収：<%= u.desired_salary %>万円</p>
                  <p>現在の職種：<%= u.employment_status %></p>
                  <%= link_to '求職者の詳細をみる', user_views_show_path(user_id: u.id) %><br>
                  <% if u.scouts.find_by(:client_id => current_client.id).blank? %>
                    <p><%= link_to 'スカウトの新規作成', new_scout_path(user_id: u.id) %></p>
                  <% else %>
                    <P>ステータス：スカウト送付済</P>
                  <% end %>
                </div><!-- text -->
            </div><!--frame_index-->
          <% end %>  <!-- if 文の終了 -->
      <% end %>
    </div><!--scout-job-content-index -->
<!-- 求職者情報の一覧ページ終了 -->
</div>
<div class="menu-back">
  <%= link_to 'スカウト管理画面へ戻る', scout_manage_path %><br>
</div>

app/views/scouts/new.html.erb
<div class="content_upper">
  <h3>スカウトをする</h3>
</div>
<div class="setting-container-detail-form">
<%= render 'form' , Scout: @scout%>
</div>

app/views/scouts/show.html.erb
<div class="content_upper">
  <h2>スカウト送付確認画面</h2>
</div>

<div class="content_container">
  <p> <%= @user.number_id %>さんへ</br>以下の登録文でスカウトメッセージを作成しました。</p>
  <table class="table_1">
    <tr>
      <th>要件</th>
      <td><%= @scout.summary %></td>
    </tr>
    <tr>
      <th>スカウトメッセージ</th>
      <td><%= @scout.content %></td>
    </tr>
  </table>
</div>

<div class="menu-back">
  <%= link_to "スカウト送付ページへ戻る" , :action => 'index' %>
</div>